// Generates a NEW throwaway wallet for GenLayer Studionet and stores it in .env.
// The private key is written to .env (gitignored) and is never printed.
import { existsSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { generatePrivateKey, createAccount } from "genlayer-js";

const ENV_PATH = new URL("../.env", import.meta.url);
const force = process.argv.includes("--force");

let existing = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, "utf8") : "";
if (/^PRIVATE_KEY=0x[0-9a-fA-F]{64}$/m.test(existing) && !force) {
  console.error(".env already contains PRIVATE_KEY. Use --force to replace it.");
  process.exit(1);
}

const privateKey = generatePrivateKey();
const account = createAccount(privateKey);

const kept = existing
  .split("\n")
  .filter((line) => line && !line.startsWith("PRIVATE_KEY=") && !line.startsWith("WALLET_ADDRESS="));
const lines = [
  "# Generated by scripts/create-wallet.mjs - NEVER commit this file",
  ...kept.filter((l) => !l.startsWith("# Generated by")),
  `PRIVATE_KEY=${privateKey}`,
  `WALLET_ADDRESS=${account.address}`,
];
if (!kept.some((l) => l.startsWith("GENLAYER_RPC_URL="))) {
  lines.push("GENLAYER_RPC_URL=https://studio.genlayer.com/api");
}
writeFileSync(ENV_PATH, lines.join("\n") + "\n");
chmodSync(ENV_PATH, 0o600);

console.log(`New wallet address: ${account.address}`);
console.log("Private key saved to .env (not printed).");
